[package]
name = "trait-test"
version = "0.1.0"
authors = ["John Doe <smthwnsn14@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
